# SQL Notebook Sample:

In [75]:
import pandas as pd
import sys
!{sys.executable} -m pip install pandasql -q
from pandasql import sqldf

customers = pd.read_csv('customers.csv')
transactions = pd.read_csv('transactions.csv')
marketing_campaigns = pd.read_csv('marketing_campaigns.csv')
customer_events = pd.read_csv('customer_events.csv')
monthly_cohort_metrics = pd.read_csv('monthly_cohort_metrics.csv')
daily_acquisition_stats = pd.read_csv('daily_acquisition_stats.csv')

## Select all columns

In [76]:
sqldf("""
    SELECT *
    FROM customers
    LIMIT 100;
""")

,customer_id,signup_date,cohort_month,acquisition_channel,acquisition_campaign,acquisition_cost,country,age,gender,plan_type,is_active,churn_date,lifetime_days,predicted_ltv,risk_score
0,1,2023-10-17,2023-10,paid_search,spring_promo,63.20,UK,32,M,free,1,None,289,69.08,0.59
1,2,2022-02-02,2022-02,organic_search,summer_sale,1.09,FR,56,M,free,1,None,911,69.04,0.23
2,3,2023-08-27,2023-08,email,spring_promo,11.86,US,62,M,free,0,2024-08-12,351,29.20,0.38
3,4,2023-01-03,2023-01,direct,product_hunt,0.79,US,64,M,free,1,None,576,27.09,0.30
4,5,2023-10-06,2023-10,direct,product_hunt,0.58,US,20,F,pro,1,None,300,1551.66,0.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2022-07-25,2022-07,social_media,webinar_series,53.82,CA,51,F,free,0,2023-12-07,500,107.06,0.30
96,97,2024-06-10,2024-06,direct,summer_sale,1.40,US,27,F,free,1,None,52,80.70,0.40
97,98,2024-05-16,2024-05,direct,summer_sale,2.37,US,34,F,basic,1,None,77,483.06,0.58
98,99,2024-04-22,2024-04,direct,summer_sale,2.02,DE,19,F,enterprise,1,None,101,4494.44,0.64
99,100,2023-10-13,2023-10,content_marketing,brand_awareness,21.23,US,26,M,free,1,None,293,30.45,0.24

## Select specific columns

In [77]:
# Retrieve the first 10 rows from the customers table.

sqldf ("""
    SELECT customer_id, signup_date, plan_type
    FROM customers
    LIMIT 10;
""")

   customer_id signup_date plan_type
0            1  2023-10-17      free
1            2  2022-02-02      free
2            3  2023-08-27      free
3            4  2023-01-03      free
4            5  2023-10-06       pro
5            6  2023-01-25      free
6            7  2024-01-17      free
7            8  2022-11-20       pro
8            9  2022-09-29     basic
9           10  2022-05-22       pro

## WHERE with one condition

In [78]:
# Find all customers on the enterprise plan.

sqldf ("""
    SELECT customer_id
    FROM customers
    WHERE plan_type = 'enterprise'
    LIMIT 10;
""")

   customer_id
0           21
1           22
2           37
3           46
4           64
5           74
6           81
7           86
8           91
9           93

## WHERE with multiple conditions (AND)

In [84]:
# Find customers who signed up after 2023-01-01 AND are on the pro plan.

sqldf ("""
       SELECT customer_id
       FROM customers
       WHERE signup_date > '2023-01-01'
       AND plan_type = 'pro';
""")

     customer_id
0              5
1             11
2             16
3             28
4             33
..           ...
140          981
141          985
142          986
143          988
144         1000

[145 rows x 1 columns]

## WHERE with OR

In [80]:
# Find customers from the US or UK.

sqldf ("""
    SELECT *
    FROM customers
    WHERE country = 'US' OR 'UK';
""")

,customer_id,signup_date,cohort_month,acquisition_channel,acquisition_campaign,acquisition_cost,country,age,gender,plan_type,is_active,churn_date,lifetime_days,predicted_ltv,risk_score
0,3,2023-08-27,2023-08,email,spring_promo,11.86,US,62,M,free,0,2024-08-12,351,29.20,0.38
1,4,2023-01-03,2023-01,direct,product_hunt,0.79,US,64,M,free,1,None,576,27.09,0.30
2,5,2023-10-06,2023-10,direct,product_hunt,0.58,US,20,F,pro,1,None,300,1551.66,0.86
3,10,2022-05-22,2022-05,content_marketing,summer_sale,23.89,US,27,F,pro,1,None,802,411.48,0.38
4,11,2023-04-25,2023-04,email,webinar_series,13.19,US,61,F,pro,1,None,464,704.23,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,978,2022-01-22,2022-01,social_media,brand_awareness,54.06,US,61,F,free,0,2023-05-29,492,72.48,0.49
236,979,2022-09-11,2022-09,content_marketing,summer_sale,6.13,US,54,F,free,0,2024-02-15,522,35.06,0.15
237,997,2022-05-20,2022-05,referral,None,17.79,US,37,F,pro,1,None,804,1480.09,0.62
238,999,2022-02-26,2022-02,paid_search,brand_awareness,41.30,US,33,F,basic,1,None,887,487.91,0.85
239,1000,2023-09-24,2023-09,paid_search,influencer_q1,24.51,US,29,M,pro,1,None,312,1056.58,0.70

## IN operator

In [81]:
# Same as above but using IN — find customers from US, UK, or CA.

sqldf ("""
    SELECT *
    FROM customers
    WHERE country IN ('US', 'UK', 'CA');
""")

,customer_id,signup_date,cohort_month,acquisition_channel,acquisition_campaign,acquisition_cost,country,age,gender,plan_type,is_active,churn_date,lifetime_days,predicted_ltv,risk_score
0,1,2023-10-17,2023-10,paid_search,spring_promo,63.20,UK,32,M,free,1,None,289,69.08,0.59
1,3,2023-08-27,2023-08,email,spring_promo,11.86,US,62,M,free,0,2024-08-12,351,29.20,0.38
2,4,2023-01-03,2023-01,direct,product_hunt,0.79,US,64,M,free,1,None,576,27.09,0.30
3,5,2023-10-06,2023-10,direct,product_hunt,0.58,US,20,F,pro,1,None,300,1551.66,0.86
4,6,2023-01-25,2023-01,email,influencer_q2,10.26,CA,28,M,free,0,2023-04-15,80,74.82,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,991,2022-05-19,2022-05,affiliate,webinar_series,29.98,UK,23,M,enterprise,1,None,805,2190.21,0.78
479,995,2023-06-15,2023-06,content_marketing,spring_promo,7.12,UK,59,M,basic,1,None,413,425.34,0.69
480,997,2022-05-20,2022-05,referral,None,17.79,US,37,F,pro,1,None,804,1480.09,0.62
481,999,2022-02-26,2022-02,paid_search,brand_awareness,41.30,US,33,F,basic,1,None,887,487.91,0.85
482,1000,2023-09-24,2023-09,paid_search,influencer_q1,24.51,US,29,M,pro,1,None,312,1056.58,0.70

## BETWEEN

In [83]:
# Find transactions with amounts between 100 and 500.

sqldf ("""
    SELECT *
    FROM transactions
    WHERE amount BETWEEN 100 AND 500
    LIMIT 20;
""")

,transaction_id,customer_id,transaction_date,amount,product_category,payment_method,is_refund,discount_pct
0,1,1,2024-03-13,479.36,one_time_purchase,wire_transfer,0,5
1,4,2,2023-01-31,260.56,training,credit_card,0,5
2,5,3,2023-12-12,214.10,subscription,debit_card,0,0
3,7,5,2024-04-15,322.63,training,ach,0,25
4,8,5,2024-02-15,103.65,subscription,ach,0,10
5,11,5,2023-11-28,430.60,professional_services,credit_card,0,15
6,13,5,2024-04-14,422.53,one_time_purchase,credit_card,0,10
7,14,5,2024-05-23,295.78,subscription,debit_card,0,0
8,17,5,2023-10-23,179.73,upgrade,ach,0,15
9,19,5,2024-01-11,118.37,upgrade,paypal,0,10
10,21,8,2022-12-13,281.84,subscription,wire_transfer,0,5
11,22,8,2023-11-21,261.85,subscription,ach,0,0
12,23,8,2024-07-01,159.63,subscription,wire_transfer,0,5
13,27,8,2024-04-08,283.97,subscription,paypal,0,0
14,30,8,2024-04-22,111.22,subscription,credit_card,0,0
15,31,8,2023-01-15,235.94,subscription,credit_card,0,15
16,33,9,2023-12-21,187.92,subscription,debit_card,0,10
17,35,9,2023-11-25,445.40,one_time_purchase,credit_card,0,0
18,37,9,2022-11-12,184.09,subscription,debit_card,0,5
19,38,9,2024-06-10,200.04,subscription,paypal,0,0

## LIKE (pattern matching)

In [93]:
# Find all campaigns with "04" in the name.

sqldf ("""
    SELECT *
    FROM marketing_campaigns
    WHERE campaign_name LIKE '%04%';
""")

,campaign_id,campaign_name,channel,start_date,end_date,budget,spend,impressions,clicks,conversions,target_audience
0,4,campaign_004,organic_search,2023-11-13,2024-01-25,6561.07,4187.47,427357,28548,2589,returning
1,40,campaign_040,email,2023-04-28,2023-07-24,5488.91,4949.17,73972,4103,587,enterprise_prospects
2,41,campaign_041,referral,2024-02-11,2024-04-29,30316.39,28150.50,291359,8299,1134,enterprise_prospects
3,42,campaign_042,paid_search,2023-05-28,2023-07-11,28953.55,25545.48,321116,18042,2338,smb
4,43,campaign_043,direct,2023-08-28,2023-10-18,11919.20,9019.02,404405,21589,2115,returning
5,44,campaign_044,organic_search,2022-05-17,2022-08-02,36059.22,32219.79,173659,1899,282,new_users
6,45,campaign_045,paid_search,2023-07-16,2023-08-03,25330.44,18639.85,306552,12051,1441,new_users
7,46,campaign_046,paid_search,2022-10-22,2023-01-14,21740.34,15098.18,450964,3115,282,new_users
8,47,campaign_047,paid_search,2022-11-19,2022-11-26,14809.86,15518.99,173939,8764,619,developers
9,48,campaign_048,content_marketing,2023-11-02,2024-01-05,45093.64,46580.19,37294,264,29,enterprise_prospects
10,49,campaign_049,social_media,2024-03-06,2024-05-18,11188.91,11300.64,157492,5011,579,new_users

## ORDER BY

In [96]:
# Show all customers sorted by acquisition_cost from highest to lowest.

sqldf ("""
    SELECT *
    FROM customers
    ORDER BY acquisition_cost DESC;
""")

,customer_id,signup_date,cohort_month,acquisition_channel,acquisition_campaign,acquisition_cost,country,age,gender,plan_type,is_active,churn_date,lifetime_days,predicted_ltv,risk_score
0,871,2022-10-15,2022-10,paid_search,brand_awareness,79.63,UK,60,F,free,1,None,656,92.90,0.70
1,161,2023-08-12,2023-08,paid_search,fall_launch,78.20,IN,22,M,pro,1,None,355,1584.26,0.77
2,74,2022-01-27,2022-01,paid_search,winter_deal,77.52,BR,55,F,enterprise,1,None,917,2655.36,0.05
3,790,2022-07-16,2022-07,paid_search,winter_deal,77.32,US,60,M,free,0,2022-11-10,117,93.41,0.33
4,678,2024-02-01,2024-02,paid_search,webinar_series,76.87,AU,23,M,free,1,None,182,97.90,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,926,2022-08-07,2022-08,direct,product_hunt,0.09,BR,42,M,pro,1,None,725,1729.13,0.22
996,959,2022-08-31,2022-08,organic_search,brand_awareness,0.09,BR,18,F,free,1,None,701,56.25,0.89
997,14,2023-09-06,2023-09,direct,influencer_q2,0.06,CA,37,M,free,1,None,330,27.09,0.73
998,484,2023-11-10,2023-11,direct,summer_sale,0.06,IN,42,M,basic,1,None,265,173.79,0.32
999,553,2022-11-17,2022-11,organic_search,None,0.04,US,18,M,basic,1,None,623,309.82,0.72